exercise_app/config/routes.rb
ExerciseApp::Application.routes.draw do

  get "sessions/new"

  resources :articles, :users, :products, :categories, :countries, :comments
  get "articles/index"
  root :to => "sessions#new"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in" 
  resources :sessions
  get "log_out" => "sessions#destroy", :as => "log_out"
  namespace :admin do
    resources :articles
  end
end

exercise_app/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  scope :rating, lambda {|rating| where("rating = ?", rating)}
  attr_accessible :title, :description, :rating, :user_id
  validates :title, :presence => { :message => "You must fill title" },
  		              :uniqueness => true
  validates :description, :presence => { :message => "You must fill description" }
  validates :rating, :presence => { :message => "You must fill rating" }
  validates :user_id, :presence => { :message => "You must fill users_id" }		  
  def self.more_than_100
    where(" length(description) > 100")
  end
end

exercise_app/app/models/articles.rb
class Articles < ActiveRecord::Base
  belongs_to :users
  has_many :comments, :dependent => :destroy
  scope :rating, lambda {|rating| where("rating = ?", rating)}
  attr_accessible :title, :description, :rating, :users_id
  validates :title, :presence => { :message => "You must fill title" },
  		    :uniqueness => true
  validates :description, :presence => { :message => "You must fill description" }
  validates :rating, :presence => { :message => "You must fill rating" }
  validates :users_id, :presence => { :message => "You must fill users_id" }		  
  def self.more_than_100
    where(" length(description) > 100")
  end
end

exercise_app/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_filter :require_admin_login
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "Creating succeed"
      redirect_to :action => 'index'
    else
      flash[:notice] = "Creating failed"
      render :action => 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "Updating succeed"
      redirect_to :action => :index
    else
      flash[:notice] = "Updating failed"
      render :action => :edit
    end
  end
  
  def welcome
    render :text => "Welcome to Ruby on Rails"
  end
  def show
      @article = Article.find(params[:id])
      @comments = Comment.find_all_by_article_id(params[:id])
      @comment = Comment.new
  end
  def destroy
    @article = Article.find(params[:id])
    if @article.user_id == session[:user_id]
      flash[:notice] = "Article is deleted."
      @article.destroy
      redirect_to admin_articles_path
    else
      flash[:notice] = "Unauthorized to delete the article."
      redirect_to admin_articles_path
    end
    
  end
  
end

exercise_app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #before_filter :find_product
  before_filter :require_login, :only => [:index,:new, :create, :edit, :update, :destroy]
  before_filter :find_article, :only => [:edit, :update, :show, :destroy]
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to (@article)
    else
      flash[:error] = 'Article was failed to create.'
      render :action => 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = 'Article was successfully updated.'
      redirect_to(@article)
    else
      flash[:error] = 'Article was failed to update.'
      render :action => "edit"
    end
  end
  
  def welcome
    render :text => "Welcome to Ruby on Rails"
  end
  def show
      @article = Article.find(params[:id])
      @comments = Comment.find_all_by_article_id(params[:id])
      @comment = Comment.new
  end
  def destroy
    
    @article = Article.find(params[:id])
    if @article.user_id == session[:user_id]
      #flash[:notice] = "Article is deleted."
      @article.destroy ? (flash[:error] = "Article successfully deleted") :
                    (flash[:notice] = "Article failed to delete")
      redirect_to articles_url
    else
      @article.destroy ? (flash[:error] = "Article successfully deleted") :
                    (flash[:notice] = "Article failed to delete")
      redirect_to articles_url
    end
    
  end
  private
    def find_article
      @article = Article.find_by_id(params[:id])
      if @article.nil?
        flash[:notice] = "Cannot find the article"
        redirect_to articles_url
      end
    end
end

exercise_app/app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

exercise_app/app/helpers/articles_helper.rb
module ArticlesHelper
end

exercise_app/app/views/admin/articles/_comments.html.erb
<% @comments.each do |comment| %>
    <%= comment.content %><br />
  <% end %>

exercise_app/app/views/admin/articles/edit.html.erb
<h1>Edit Article Detail</h1>
<%= form_for @article do |f| %>
<p>
  <label >Title</label> :
  <%= f.text_field :title %>
</p>
<p>
  <label >Description</label> :
  <%= f.text_field :description %>
</p>
<p>
  <label >Rating</label> :
  <%= f.text_field :rating %>
</p>
<p>
  <label >User ID</label> :
  <%= f.text_field :user_id %>
</p>

<%= f.submit  "Save changes" %>
<% end %> <br />

exercise_app/app/views/admin/articles/index.html.erb
<h1>List of Articles</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Options</th>
    </tr>
  </thead>

  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article %></td>
      <td>
        <%= link_to 'Edit', edit_admin_article_path(article.id) %>
        <%= link_to 'Delete', admin_article_path(article.id), :method => :delete, :data => { confirm: 'Are you sure?' }  %>
      </td>
    </tr>
  <% end -%>
</table>

<p><%= link_to 'New Article', new_admin_article_path %></p>

exercise_app/app/views/admin/articles/new.html.erb
<h1>Add New Article</h1>
<%= form_for @article do |f| %> 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 
  Title: <%= f.text_field :title %>  <br />
  Description : <%= f.text_field :description %>  <br />
  Rating : <%= f.text_field :rating %>  <br />
  User Id : <%= f.text_field :user_id %>  <br />
  <%=f.submit :create %>
<% end %>

exercise_app/app/views/admin/articles/show.html.erb
<!--This section is to show all comments that owned by the article  -->
<h1><%= @article.title.capitalize %></h1>
<p>
  <%= @article.description %>
</p>


<a href="/articles/<%= @article.id %>/edit">Edit Article</a>

<h2>Comments</h2>
<div id="comments">
  <%= render :partial => "comments", :locals => {:comments => @comments}  %>
</div><br /><br />

<h4>Add New Comment</h4>
<% unless(current_user.nil?)%>
   <%= form_for @comment, :url => comments_path, :remote => true do |f| -%>
      <%= f.text_area :content %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :article_id, :value => @article.id %><br />
      <%= submit_tag "comment" %>
  <% end -%>
<% end %>