exercise_app/config/routes.rb
ExerciseApp::Application.routes.draw do

  get "sessions/new"

  resources :articles, :users, :products, :categories, :countries, :comments
  get "articles/index"
  root :to => "sessions#new"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in" 
  resources :sessions
  get "log_out" => "sessions#destroy", :as => "log_out"
  namespace :admin do
    resources :articles
  end
end

exercise_app/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :categories
  #has_many :categories, :through => :categories_products
  scope :stock, lambda { |stock| where('stock = ?' , stock) }
  scope :price_less_than, lambda { |price| where('price < ?' , price) }
  validates :price, :presence => { :message => "You must fill price" }, :numericality => true
  validates :description, :presence => { :message => "You must fill description" }
  validates :name, :presence => { :message => "You must fill name" }
  validates :stock, :presence => { :message => "You must fill stock" }
  validates :user_id, :presence => { :message => "You must fill user_id" }
  attr_accessible :description, :name, :price, :stock, :user_id
end

exercise_app/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_login, :only => [:index,:new, :create, :edit, :update, :destroy]
  before_filter :find_product, :only => [:edit, :update, :show, :destroy]
  def index
    @products = Product.all
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "Product was successfully created."
      redirect_to (@product)
    else
      flash[:error] = 'Product was failed to create.'
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      flash[:notice] = 'Product was successfully updated.'
      redirect_to(@product)
    else
      flash[:error] = 'Product was failed to update.'
      render :action => "edit"
    end
  end
  
  def welcome
    render :text => "Welcome to Ruby on Rails"
  end
  def show
      @product = Product.find(params[:id])
  end
  def destroy
    
    @product = Product.find(params[:id])
    if @product.user_id == session[:user_id]
      #flash[:notice] = "Product is deleted."
      @product.destroy ? (flash[:error] = "Product successfully deleted") :
                    (flash[:notice] = "Product failed to delete")
      redirect_to products_url
    else
      @product.destroy ? (flash[:error] = "Product successfully deleted") :
                    (flash[:notice] = "Product failed to delete")
      redirect_to products_url
    end
    
  end
  private
    def find_product
      @product = Product.find_by_id(params[:id])
      if @product.nil?
        flash[:notice] = "Cannot find the product"
        redirect_to products_url
      end
    end
  
end

exercise_app/app/helpers/products_helper.rb
module ProductsHelper
end

exercise_app/app/views/products/edit.html.erb
<h1>Edit Product Detail</h1>
<%= form_for @product do |f| %>
<p>
  <label >Name</label> :
  <%= f.text_field :name %>
</p>
<p>
  <label >Price</label> :
  <%= f.text_field :price %>
</p>
<p>
  <label >Stock</label> :
  <%= f.text_field :stock %>
</p>
<p>
  <label >Description</label> :
  <%= f.text_field :description %>
</p>
<p>
  <label >User ID</label> :
  <%= f.text_field :user_id %>
</p>

<%= f.submit  "Save changes" %>
<% end %> <br />

exercise_app/app/views/products/index.html.erb
<h1>List of Products</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Options</th>
    </tr>
  </thead>

  <% @products.each do |product| %>
    <tr>
      <td><%= link_to product.name, product %></td>
      <td>
        <%= link_to 'Edit', edit_product_path(product.id) %>
        <%= link_to 'Delete', product_path(product.id), :method => :delete, :data => { confirm: 'Are you sure?' }  %>
      </td>
    </tr>
  <% end -%>
</table>

<p><%= link_to 'New Product', new_product_path %></p>

exercise_app/app/views/products/new.html.erb
<h1>Add New Product</h1>
<%= form_for @product do |f| %>  
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  Name : <%= f.text_field :name %>  <br />
  Price : <%= f.text_field :price %>  <br />
  Stock : <%= f.text_field :stock %>  <br />
  Description : <%= f.text_field :description %>  <br />
  User ID : <%= f.text_field :user_id %>  <br />
  <%=f.submit :create %>
<% end %>

exercise_app/app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p>
  Price : 
  <%= @product.price %>
</p>
<p>
  Stock : 
  <%= @product.stock %>
</p>
<p>
  Description : 
  <%= @product.description %>
</p>
<p>
  User ID : 
  <%= @product.user_id %>
</p>

<a href="/products/<%= @product.id %>/edit">Edit</a>