exercise_app/config/routes.rb
ExerciseApp::Application.routes.draw do

  get "sessions/new"

  resources :articles, :users, :products, :categories, :countries, :comments
  get "articles/index"
  root :to => "sessions#new"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in" 
  resources :sessions
  get "log_out" => "sessions#destroy", :as => "log_out"
  namespace :admin do
    resources :articles
  end
end

exercise_app/app/models/user.rb
class User < ActiveRecord::Base
  has_many :products
  has_many :articles
  has_many :comments
  belongs_to :country 
  has_many :my_country,
           :class_name => "Article",
           :foreign_key => "user_id",
           :conditions => "title like '%my country%'"
  
  #scope :indo, lambda { joins(:countries).merge(Country.indo)}
  #scope :indo, where(:country_id=>'5')
  #scope :indo, where(:country_id=>Country.indo[0].id)
  scope :indo, where("countries.name LIKE '%indonesia%'").includes(:country)
  validates :first_name, :presence => { :message => "You must fill first name" },
			:length => {:minimum => 1, :maximum => 25 },
			:uniqueness => true, 
			:format => {:with => /[a-zA-Z\s]+$/}
  validates :last_name, :presence => { :message => "You must fill last name" },
			:length => {:minimum => 1, :maximum => 25 },
			:uniqueness => true, 
			:format => {:with => /[a-zA-Z\s]+$/}
  validates :email, :presence => { :message => "You must fill e-mail" },
			:uniqueness => true, 
			:format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :username, :presence => { :message => "You must fill username" }
  validates :password, :presence => { :message => "You must fill password",:on => :create}, :confirmation => true
  validates :date_of_birth, :presence => { :message => "You must fill date_of_birth" }
  validates :age, :presence => { :message => "You must fill age" }
  validates :address, :presence => { :message => "You must fill address" }
  validates :country_id, :presence => { :message => "You must fill country_id" }
  validates_confirmation_of :password
  def show_full_address
    country = Country.find(self.country_id)
    "#{self.address} #{country.name}"
  end
  def self.age_18_more
     where("age > 18")
  end
  before_save :encrypt_password
  #attr_accessor :password
  attr_accessible :first_name, :last_name, :email, :username, :password, :date_of_birth, :age, :address, :country_id, :password_confirmation, :admin
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
     user
    else
      nil
    end
  end

  def is_admin?
    if self.admin
      return true
    else
      return false
    end
  end
end

exercise_app/app/models/users.rb
class Users < ActiveRecord::Base
  has_many :products
  has_many :articles
  has_many :comments
  belongs_to :countries 
  has_many :my_country,
           :class_name => "Articles",
           :foreign_key => "users_id",
           :conditions => "title like '%my country%'"
  #default_scope where("countries_id = '1'")
  scope :indo, joins(:countries).merge(Countries.indo)
  validates :first_name, :presence => { :message => "You must fill first name" },
			:length => {:minimum => 1, :maximum => 25 },
			:uniqueness => true, 
			:format => {:with => /[a-zA-Z\s]+$/}
  validates :last_name, :presence => { :message => "You must fill last name" },
			:length => {:minimum => 1, :maximum => 25 },
			:uniqueness => true, 
			:format => {:with => /[a-zA-Z\s]+$/}
  validates :email, :presence => { :message => "You must fill e-mail" },
			:uniqueness => true, 
			:format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :username, :presence => { :message => "You must fill username" }
  validates :password, :presence => { :message => "You must fill password" }
  validates :date_of_birth, :presence => { :message => "You must fill date_of_birth" }
  validates :age, :presence => { :message => "You must fill age" }
  validates :address, :presence => { :message => "You must fill address" }
  validates :countries_id, :presence => { :message => "You must fill countries_id" }
  def show_full_address
    country = Countries.find(self.countries_id)
    "#{self.address} #{country.name}"
  end
  def self.age_18_more
     where("age > 18")
  end
  attr_accessible :first_name, :last_name, :email, :username, :password, :date_of_birth, :age, :address, :countries_id
end

exercise_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:index,:new, :create, :edit, :update, :destroy]
  before_filter :find_user, :only => [:edit, :update, :show, :destroy]
  


  def index
    @users = User.find(:all)
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if verify_recaptcha
      
      if @user.save 
        UserMailer.registration_confirmation(@user).deliver
        flash[:notice] = "User was successfully created."
        redirect_to (@user)
        #redirect_to root_url, :notice => "Signed up!" 
      else
        flash[:error] = 'User was failed to create.'
        render :action => 'new'
      end
    else
      flash[:error] = "There was an error with the recaptcha code below.
                       Please re-enter the code and click submit."
      render "new"
    end

  end
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User was successfully updated.'
      redirect_to(@user)
    else
      flash[:error] = 'User was failed to update.'
      render :action => "edit"
    end
  end
  def show
      @user = User.find(params[:id])
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy ? (flash[:error] = "User successfully deleted") :
                  (flash[:notice] = "User failed to delete")
    redirect_to users_url
  end
  private
    def find_user
      @user = User.find_by_id(params[:id])
      if @user.nil?
        flash[:notice] = "Cannot find the user"
        redirect_to users_url
      end
    end

end

exercise_app/app/helpers/users_helper.rb
module UsersHelper
end

exercise_app/app/views/users/edit.html.erb
<h1>Edit User Detail</h1>
<%= form_for @user do |f| %>
<p>
  <label >First Name</label> :
  <%= f.text_field :first_name %>
</p>
<p>
  <label >Last Name</label> :
  <%= f.text_field :last_name %>
</p>
<p>
  <label >Email</label> :
  <%= f.text_field :email %>
</p>
<p>
  <label >Username</label> :
  <%= f.text_field :username %>
</p>
<p>
  <label >Password</label> :
  <%= f.text_field :password %>
</p>
<p>
  <label >Date of Birth</label> :
  <%= f.text_field :date_of_birth %>
</p>
<p>
  <label >Age</label> :
  <%= f.text_field :age %>
</p>
<p>
  <label >Address</label> :
  <%= f.text_field :address %>
</p>
<p>
  <label >Countries ID</label> :
  <%= f.text_field :country_id %>
</p>

<%= f.submit  "Save changes" %>
<% end %> <br />

exercise_app/app/views/users/index.html.erb
<h1>List of Users</h1>

<table border="1">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Options</th>
    </tr>
  </thead>

  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.first_name, user %></td>
      <td>
        <%= link_to 'Edit', edit_user_path(user.id) %>
        <%= link_to 'Delete', user_path(user.id), :method => :delete, :data => { confirm: 'Are you sure?' }  %>
      </td>
    </tr>
  <% end -%>
</table>

<p><%= link_to 'New User', new_user_path %></p>

exercise_app/app/views/users/new.html.erb
<%= flash[:error] %>
<h1>Sign Up</h1>
<%= form_for @user do |f| %>  
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  First Name : <%= f.text_field :first_name %>  <br />
  Last Name : <%= f.text_field :last_name %>  <br />
  Email : <%= f.text_field :email %>  <br />
  Username : <%= f.text_field :username %>  <br />
  Password : <%= f.password_field :password %>  <br />
  Confirm Password  : <%= f.password_field :password_confirmation %> <br />
  Date of Birth : <%= f.text_field :date_of_birth %>  <br />
  Age : <%= f.text_field :age %>  <br />
  Address : <%= f.text_field :address %>  <br />
  Country : <%= f.collection_select :country_id, Country.all, :id, :name %> <br />
  <%= recaptcha_tags %>
  <%=f.submit :create %>
<% end %>

exercise_app/app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1> 
<p>
  <%= @user.email %>
</p>

<a href="/users/<%= @user.id %>/edit">Edit</a>